### ISSUE TITLE
Exception error when build and run with 2.0.0-beta1 version

### ISSUE THREAD

**Issue by YuyingAnnZhang** [Yubico/yubikit-android#39] opened 2021-02-23 20:22 UTC
Hello Yubikey developers:
I am developing a simple Android app with Yubikey for our two factor authentication prototype.  
The app works well when I built it with the downloaded yubikit-android project (https://github.com/Yubico/yubikit-android), i.e., it builds and runs fine when it is part of the downloaded project as it depends on the android and yubiotp modules in the same project.
 
The app gives runtime errors when I build it standalone with your 2.0.0-beta01 library release that’s available.   
Here is the runtime error message I got on USB device attached when I run the prototype
 
java.lang.NoSuchMethodError: No virtual method flip()Ljava/nio/ByteBuffer; 
in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)

And here is the stack trace:

0 = {StackTraceElement@5211} "com.yubico.yubikit.core.otp.OtpProtocol.sendFrame(OtpProtocol.java:150)"
1 = {StackTraceElement@5212} "com.yubico.yubikit.core.otp.OtpProtocol.sendAndReceive(OtpProtocol.java:82)"
2 = {StackTraceElement@5213} "com.yubico.yubikit.yubiotp.YubiOtpSession$2.sendAndReceive(YubiOtpSession.java:210)"
3 = {StackTraceElement@5214} "com.yubico.yubikit.yubiotp.YubiOtpSession.calculateHmacSha1(YubiOtpSession.java:372)"
4 = {StackTraceElement@5215} "org.rti.nsduh.yubikey.ui.login.LoginActivity$3$1.onDeviceAttached(LoginActivity.java:170)"
5 = {StackTraceElement@5216} "com.yubico.yubikit.android.transport.usb.UsbYubiKeyManager$MyDeviceListener.deviceAttached(UsbYubiKeyManager.java:69)"
6 = {StackTraceElement@5217} "com.yubico.yubikit.android.transport.usb.UsbDeviceManager.lambda$addUsbListener$0(UsbDeviceManager.java:73)"
7 = {StackTraceElement@5218} "com.yubico.yubikit.android.transport.usb.-$$Lambda$UsbDeviceManager$zQEUuPNqclVb1kIWdk9yCYJUi8A.run(lambda)"
8 = {StackTraceElement@5219} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)"
9 = {StackTraceElement@5220} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)"
10 = {StackTraceElement@5221} "java.lang.Thread.run(Thread.java:762)"
 
Its the buf.flip() call in sendFrame() method of the file OtpProtocol.java file that gives the exception.

Can you please update 2.0.0-beta01 Jar files so that it will work as well as your Github library code?  If the source code is identical, please document what we need to do so that we don't get the runtime error.

The only difference I made for my prototype is switching from the dependency in my build.gradle file from
      implementation project(path: ':android')   //this works
      implementation project(path: ':yubiotp')    //this works
to this
    implementation 'com.yubico.yubikit:android:2.0.0-beta01'   //2.0-beta01 gives runtime errors
    implementation 'com.yubico.yubikit:yubiotp:2.0.0-beta01'   //2.0-beta01 gives runtime errors

Thank you for your time, hope I will get a solution soon.

**Comment by dainnilsson** [comment] 2021-02-24 16:53
Thank you for reporting this! I wasn't able to reproduce the issue, but I believe I've still managed to figure out what is wrong. It seems the beta01 jar files were built without full Java 8 compatibility, even though the source is fully Java 8 compatible. I've just released `2.0.0-beta02` which should fix this. Note that this new beta has a few other changes as well, so you may need to update your code slightly. Please let me know if you run into any issues in doing so, and I'll gladly help out!

**Comment by YuyingAnnZhang** [comment] 2021-02-24 17:36
Thanks for such a quick update.   My code no longer compiles, there two import statements are no longer good:
import com.yubico.yubikit.android.transport.nfc.NfcYubiKeyListener;
import com.yubico.yubikit.android.transport.usb.UsbYubiKeyListener;
Do you know which package they move to? 
Thanks a lot.

**Comment by dainnilsson** [comment] 2021-02-24 17:39
Those classes have been replaced with the `com.yubico.yubikit.core.util.Callback` class.

See the updated documentation here for an example on how to use it: https://github.com/Yubico/yubikit-android/blob/master/android/README.adoc

**Comment by YuyingAnnZhang** [comment] 2021-02-25 20:44
Beta2.0 works!!  I don't get that exception message anymore.

I did notice one thing that is different from all other apps I built before.  During the debug session, the app will always crash on requestConnection() for NFC discovery, but it works great in running mode, the app doesn't crash.  Do you have a clue why debug vs run mode makes a difference?  The app works nicely as long as I am not debugging it line by line.

**Comment by dainnilsson** [comment] 2021-03-03 09:30
Great! Happy to hear that the issue is resolved by beta 2.
I'm not very familiar with line by line debugging on Android, but I would think it may be a timing thing. NFC is quite sensitive and pausing execution during critical moments may very well be causing problems like this.
If you have an easy way to reproduce this feel free to open a new issue with that and we can take a look!

**Closed by dainnilsson** 2021-03-03 09:30 UTC
